/**
 * JS stand-in for the C++ code generator.
 * Emits a readable C++ sketch from tokenizer output until the native
 * compiler is wired through WASM or a backend call.
 */
class Compiler {
    compile(input) {
        const tokenText = typeof input === "string"
            ? input
            : new Tokenizer().tokenize(input);

        if (!tokenText || tokenText.includes("No simulation data")) {
            return "// No tokens to compile. Simulate a layout first.";
        }

        const tokenLines = tokenText
            .split("\n")
            .filter(line => line.trim().startsWith("tokens "))
            .map(line => line.replace("tokens", "").trim())
            .filter(line => line && line !== "(none)");

        const body = tokenLines.length
            ? tokenLines.map((line, i) => `    // element ${i + 1}: ${line}`).join("\n")
            : "    // (no tokens)";

        return [
            "// Generated by Coaster Code (JS preview of the C++ compiler)",
            "#include <iostream>",
            "#include <string>",
            "",
            "int main() {",
            body,
            "    return 0;",
            "}",
            ""
        ].join("\n");
    }
}
